# Generated by Django 5.2 on 2025-04-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
